### ISSUE TITLE
Add ability to download other shows

### ISSUE THREAD

**Issue by asimpson** [asimpson/oscar#3]
Like Peg plus Cat which can be found at this URL: https://producerplayer.services.pbskids.org/show-list/?shows=peg&shows_title=peg&page=1&page_size=20&available=public&sort=-encored_on&type=episode

**Comment by zastrow** [comment]
When running the Peg + Cat URL I found 3 things:
1. `format` is optional, so change line 70 to `format: Options<String>` and on line 60 change `x.format == "mp4"` to `x.format == Some("mp4".to_string())`
2. The episode naming is different, so change the `8` to `7` on line 46
3. The Peg + Cat episode titles have a `/` character and that needs to changed, otherwise Oscar tries to save to a directory it can’t find. Example Episode Title: The Race Car Problem/The Big Gig Problem

**Comment by zastrow** [comment]
Trying out the Regex package to address item 3: https://crates.io/crates/regex
